//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paycor.PayrollCorp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Inactive { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<decimal> RevenueForClientIndicator { get; set; }
        public Nullable<int> EECountForClientIndicator { get; set; }
    }
}
