//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paycor.PayrollCorp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintQueue
    {
        public long PQUID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<long> PlannerUID { get; set; }
        public Nullable<long> paygroupuid { get; set; }
        public Nullable<long> payrolluid { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string runtype { get; set; }
        public string print_status { get; set; }
        public string reportstype { get; set; }
        public Nullable<short> reportserverid { get; set; }
        public Nullable<short> printerid { get; set; }
        public Nullable<short> priority { get; set; }
        public short Check_Cnt { get; set; }
        public Nullable<System.DateTime> logout_time { get; set; }
        public Nullable<decimal> Postage { get; set; }
        public Nullable<System.DateTime> date_printed { get; set; }
        public System.DateTime date_created { get; set; }
        public string ProdSpecialist { get; set; }
        public string prodcomments { get; set; }
        public string Report_Classname { get; set; }
        public string ReleasedBy { get; set; }
        public Nullable<byte> DistCenterID { get; set; }
    }
}
